### ISSUE TITLE
Change from options() to Sys.setenv

### ISSUE THREAD

**Issue by isteves** [NCEAS/rt#16]
This change would enhance interoperability with other languages (env variables saved to a file on your disk that anything can read)

**Comment by isteves** [comment]
This is how `rsconnect` stores account information with `setAccountInfo("user", "token", "secret")`: https://github.com/rstudio/rsconnect/blob/cd0e0aa16d669197ac564d22c494d0b70345e9cf/R/accounts.R#L195

Sys env example: https://github.com/ropensci/opencage

**Comment by isteves** [comment]
^ just wanted to note that currently, you have to log-in again every time you restart your R session.  This should help address that!

Also: options can be stored in .RProfile if we want to be lazy about it.  It seems that Sys.setenv may be more secure though?  (Just a feeling since that's where my GITHUB_PAT lives.)

**Comment by amoeba** [comment]
> This should help address that!

Could you elaborate on this? Setting secrets with `Sys.setenv`?

**Comment by isteves** [comment]
When I was working on `rt` before, I was setting the `options(rt_base = "whatever")` each time I restarted my R session because it would get cleared.  

I only recently realized that you can also set these options in your `.Rprofile`.  For example, mine currently has: `options(blogdown.ext = ".Rmd", blogdown.author = "Irene Steves")`.  

On the other hand, my GITHUB_PAT is stored in my `.Renviron` and gets accessed with `Sys.getenv`.

**Comment by amoeba** [comment]
Cool 👍 thanks for the explainer!

**Comment by isteves** [comment]
Learned some neat things about environments from Jenny last week, which I thought would be worth sharing here.  (though it doesn't actually fit the RT use-case)

GitHub packages typically look for GITHUB_PAT or GITHUB_TOKEN in your Renviron, and then use `Sys.getenv()` to grab it when needed.  The `googledrive` package, however, handles tokens with _environments_ rather than via Renviron, since these tokens (like the DataONE tokens) change regularly.  

In the case of authentication in `googledrive`, this environment is called `.state`.  Jenny likened it to a bag 👜 that always exists, but gets emptied each time R gets restarted.  

The first script in the package, [`aaa.R`](https://github.com/tidyverse/googledrive/blob/c65dcfb930b133f23d19b03b5e343e6047f7787d/R/aaa.R#L32), creates `.state` and other environments for storing information.  When you [authorize googledrive](https://github.com/tidyverse/googledrive/blob/8772ec670dc5b379b0a336fb51fb0cd073818f2c/R/drive_auth.R) to do something, your tokens are saved to this `.state` environment, which other functions in the package can then access.

Another resource related resource: https://trestletech.com/2013/04/package-wide-variablescache-in-r-package/

**Comment by amoeba** [comment]
Cool, I hadn't heard of how `googledrive` did that. Thanks for sharing!

**Comment by amoeba** [comment]
I'm closing this since the package now uses just environment variables for setting the RT base URL and the user's login and password. Thanks for the good discussion and the pointers @isteves .
