### ISSUE TITLE
Finish implementation of RT API calls

### ISSUE THREAD

**Issue by amoeba** [NCEAS/rt#2]
Some are done, some are blank files. Finish first-pass implementations of these.

**Comment by isteves** [comment]
Checklist: 

- [x] rt
- [x] rt_login
- [ ] rt_logout
- [ ] rt_queue_properties
- [x] rt_search
- [x] rt_ticket_attachment
- [x] rt_ticket_attachments
- [ ] rt_ticket_create
- [ ] rt_ticket_edit
- [x] rt_ticket_history
- [ ] rt_ticket_history_comment
- [ ] rt_ticket_history_reply
- [ ] rt_ticket_links
- [ ] rt_ticket_links_edit
- [x] rt_ticket_properties
- [ ] rt_ticket_search
- [ ] rt_user_create
- [ ] rt_user_edit
- [ ] rt_user_properties

**Comment by isteves** [comment]
Note so I don't forget: set user_agent to github repo URL

**Comment by amoeba** [comment]
All done here.
