### ISSUE TITLE
Create a vignette

### ISSUE THREAD

**Issue by amoeba** [NCEAS/rt#3]
Something general purpose should do

- set up a base url
- create ticket
- comment on a ticket
- more?

**Comment by isteves** [comment]
On my to-do list: write vignettes for

- [ ] logging in/out of RT
- [ ] using the search function (with possible query parameters, etc.)

**Comment by amoeba** [comment]
Just noting this here: We decided in #25 to just change the searching vignette to an overview vignette.

**Comment by amoeba** [comment]
Working on tweaks in https://github.com/NCEAS/rt/tree/vignette-changes

**Comment by amoeba** [comment]
Added two more vignettes, `overview` and `workflows` for a total of three. Old vignette was renamed to `searching`.
