### ISSUE TITLE
RT attachment implementation

### ISSUE THREAD

**Issue by isteves** [NCEAS/rt#4]
The RT API deals with attachments in three different ways:

- Ticket Attachments: Gets a list of all attachments related to the ticket
- Ticket Attachment: Gets the metadata and content of a specific attachment
- Ticket Attachment Content: Gets the attachment data content without additional metadata or whitespace characters (but includes 2 extra lines that need to be stripped in most cases)

----

For our implementation, we can either:

- follow the API format and create three functions: `rt_ticket_attachments`, `rt_ticket_attachment`, `rt_ticket_attachment_content`
- try a pattern like this: 

```
attachment <- rt_ticket_attachment(...)
content(attachment)
```

- implement all three, but add a `content = TRUE` argument to `rt_ticket_attachment` that calls `rt_ticket_attachment_content`
- use `rt_ticket_attachment(base, ticket, attachment, raw = FALSE)`
- do some combination of the above

**Comment by isteves** [comment]
So far option 1 (follow the API format and create three functions: rt_ticket_attachments, rt_ticket_attachment, rt_ticket_attachment_content) has been implemented, but the other implementations are still open for discussion

**Comment by amoeba** [comment]
Excellent! Have you found your opinion changing in one direction or the other about having both `rt_ticket_attachment` and `rt_ticket_attachment_content` instead of just one?

**Comment by isteves** [comment]
In terms of implementation, I went for the simplest approach, which is to have two.  Right now, it seems like rt_ticket_attachment does not return the raw bytes for files that are not text.  See: rt_ticket_attachment(2, 1033) versus rt_ticket_attachment_content(2, 1033)

It does make some sense to combine it, but it's tricky

**Comment by amoeba** [comment]
As a point of comparison, it looks like the `python-rt` package has these as separate calls: https://github.com/CZ-NIC/python-rt/blob/master/rt.py#L920. Is that super-quick assessment about right?

**Comment by isteves** [comment]
Hm, looks like it.  Though now I realize that I forgot to account for the fact that RT tacks a header on, even when it returns bytes.  This is a bit of a clunky way of doing it, but do you have a better idea?

`xx$content[-c(1:20, length(xx$content), length(xx$content) - 1)]`

(basically just getting rid of the bytes that are associated with the RT header and footer, which is `RT/4.4.2 200 Ok\n\n﻿` and `\n\n`) . 

Since `\n` translates to `0a`, I can also grab everything up to the first two `0a`'s, and same with the end.  It might be more robust the second way

**Comment by amoeba** [comment]
I've done some refactoring and things look good to go now.
